// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPortfolioApp.Data;

#nullable disable

namespace WebApiPortfolioApp.Migrations.TemporaryDb
{
    [DbContext(typeof(TemporaryDbContext))]
    [Migration("20240614065430_CreateTemporaryProductsTable")]
    partial class CreateTemporaryProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WebApiPortfolioApp.Data.Entinities.TemporaryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TemporaryProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
